chore : created interfaces
oras-project/oras-dotnet pull request #10
Opened 2023-03-24 04:44 UTC by sammychinedu2ky

This tries to resolve this issue 
https://github.com/oras-project/oras-dotnet/issues/3
Yet to create the Copy type

2023-03-24 11:59 UTC, Wwwsylvia requested changes

2023-03-24 11:59 UTC, Wwwsylvia commented on OrasDotNet/Models/Descriptor.cs
> +    internal class Descriptor
We need to make it public so that users can use it.

2023-03-24 11:59 UTC, Wwwsylvia commented on OrasDotNet/Models/DescriptorOCI.cs
> +    internal class DescriptorOCI
Wondering why is it called `DescriptorOCI`? How about `MinimumDescriptor`? This type should only be used internally.

2023-03-24 11:59 UTC, Wwwsylvia commented on OrasDotNet/Interfaces/IReadOnlyStorage.cs
> +    internal interface IReadOnlyStorage
```suggestion
    public interface IReadOnlyStorage
```

2023-03-24 11:59 UTC, Wwwsylvia commented on OrasDotNet/Interfaces/IStorage.cs
> +    internal interface IStorage : IReadOnlyStorage
public

2023-03-24 11:59 UTC, Wwwsylvia commented on OrasDotNet/Interfaces/ITagResolver.cs
> +        Task<Descriptor> ResolveAsync(string reference, CancellationToken cancellationToken = default);
Should we have a `IResolver` for this?

2023-03-24 11:59 UTC, Wwwsylvia commented on OrasDotNet/Interfaces/ITagResolver.cs
> +        Task TagAsync(string reference, Descriptor descriptor, CancellationToken cancellationToken = default);
nit: 
```suggestion
        Task TagAsync(Descriptor descriptor, string reference, CancellationToken cancellationToken = default);
```

To be consistent with `oras-go`.

2023-03-24 11:59 UTC, Wwwsylvia commented on OrasDotNet/Interfaces/ITarget.cs
> +    internal interface ITarget : IStorage, ITagResolver
public.

2023-03-24 12:00 UTC, Wwwsylvia commented
BTW should the title starts with "feat: "?

2023-03-24 12:20 UTC, sammychinedu2ky commented on OrasDotNet/Interfaces/ITagResolver.cs
> +        Task<Descriptor> ResolveAsync(string reference, CancellationToken cancellationToken = default);
From the mermaid diagram, I didn't really see a base a Resolver but only the IResolver

2023-03-24 12:22 UTC, sammychinedu2ky commented on OrasDotNet/Interfaces/ITagResolver.cs
> +        Task<Descriptor> ResolveAsync(string reference, CancellationToken cancellationToken = default);
Ok no worries I've seen it in the GoLang code

2023-03-27 06:13 UTC, Wwwsylvia commented on OrasDotNet/Models/DescriptorOCI.cs
> +    internal class MinimumDescriptor
You may want to change the file name as well.

2023-03-27 06:13 UTC, Wwwsylvia commented on OrasDotNet/Models/Errors/AlreadyExistsException.cs
> +    internal class AlreadyExistsException : Exception
Sorry I don't get it😂 How do we customize the error message for this exception?

2023-03-27 06:15 UTC, sammychinedu2ky commented on OrasDotNet/Models/DescriptorOCI.cs
> +    internal class MinimumDescriptor
ooh yh that's right

2023-03-27 06:28 UTC, shizhMSFT commented on OrasDotNet/OrasDotNet.csproj
Should we just call this project `Oras`?

2023-03-27 06:28 UTC, shizhMSFT commented on OrasDotNet/Interfaces/IReadOnlyStorage.cs
> +namespace OrasDotnet.Interfaces
I'm thinking about the following namespaces
- `Oras.Content`
- `Oras.Registry`

and maybe
- `Oras.Exception`

2023-03-27 06:28 UTC, shizhMSFT commented on OrasDotNet/Interfaces/IResolver.cs
> +
nit: we should remove unnecessary empty lines.

2023-03-27 06:28 UTC, shizhMSFT commented on OrasDotNet/Interfaces/IReadOnlyStorage.cs
We need to document all code

2023-03-27 06:28 UTC, shizhMSFT commented on OrasDotNet/Models/Descriptor.cs
> +        public List<string> URLs { get; set; }
How about `IList`?
```suggestion
        public IList<string> URLs { get; set; }
```

2023-03-27 06:28 UTC, shizhMSFT commented on OrasDotNet/Models/Descriptor.cs
> +        public Dictionary<string, string> Annotations { get; set; }
How about `IDictionary`
```suggestion
        public IDictionary<string, string> Annotations { get; set; }
```

2023-03-27 08:23 UTC, sammychinedu2ky commented on OrasDotNet/OrasDotNet.csproj
Oras? hmm 🤔. That would be okay and short too.

2023-03-27 14:18 UTC, sammychinedu2ky commented
Yh I think that would be a great idea

2023-03-27 14:18 UTC, sammychinedu2ky commented
Yh I think that would be a great idea

2023-03-30 04:50 UTC, Wwwsylvia requested changes
Should we change the directory name? Also please document all codes in comments.

2023-04-13 04:32 UTC, Wwwsylvia approved these changes
LGTM

2023-04-13 04:32 UTC, Wwwsylvia commented on Oras/Interfaces/IResolver.cs
> +        /// ResolveAsync resolves the tag to a descriptor.
nit:
```suggestion
        /// ResolveAsync resolves the reference to a descriptor.
```

2023-04-13 13:00 UTC, sammychinedu2ky commented
> Please fix the DCO.

Thanks @Wwwsylvia .. its fixed now

2023-04-17 03:16 UTC, Wwwsylvia commented on Oras/Exceptions/InvalidReferenceException.cs
> +    /// InvalidDigestException is thrown when a digest is invalid.
This doc does not match the type.

2023-04-20 06:34 UTC, merged