Feat: MemoryTarget Implemented
oras-project/oras-dotnet pull request #13
Opened 2023-04-21 07:21 UTC by sammychinedu2ky

Implemented the Memory Target -> https://github.com/oras-project/oras-dotnet/issues/4

2023-04-21 11:15 UTC, Wwwsylvia commented
The PR title should start with "**f**eat:"

2023-04-21 11:25 UTC, sammychinedu2ky commented
> The PR title should start with "**f**eat:". And please use the [keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) to reference an issue.

Ok thanks, I have fixed that

2023-04-21 11:56 UTC, Wwwsylvia requested changes

2023-04-21 11:56 UTC, Wwwsylvia commented on Oras/Constants/DockerMediaTypes.cs
> +       public const string ManifestList = "application/vnd.docker.distribution.manifest.list.v2+json";
Should the constant be prefixed with `MediaType`? So it becomes `MediaTypeDockerManifestList`?
Same rule applies to other constants.

2023-04-21 11:56 UTC, Wwwsylvia commented on Oras/Constants/DockerMediaTypes.cs
> +       public const string Config = "application/vnd.docker.container.image.v1+json";
Maybe `MediaTypeDockerImageConfig`?

2023-04-21 11:56 UTC, Wwwsylvia commented on Oras/Constants/DockerMediaTypes.cs
> +    internal class DockerMediaTypes
Should we make this public?

2023-04-21 11:56 UTC, Wwwsylvia commented on Oras/Constants/OCISPECMediaTypes.cs
> +    internal class OCISPECMediaTypes
Should we make this public? Also wondering if we should name it just `MediaTypes`.

2023-04-21 11:56 UTC, Wwwsylvia commented on Oras/Interfaces/IFetcher.cs
> +    public interface IFetcher
You may also want to change `IReadOnlyStorage` to reference this.

2023-04-21 11:56 UTC, Wwwsylvia commented on Oras/Interfaces/IFetcher.cs
> +        Task<Stream> FetchAsync(Descriptor target, CancellationToken cancellationToken = default);
Documentation required.

2023-04-21 11:56 UTC, Wwwsylvia commented on Oras/Models/Artifact.cs
> +    public class Artifact
Let's remove this type and focus on [OCI spec `v1.0.2`](https://github.com/opencontainers/image-spec/tree/v1.0.2/specs-go).

2023-04-21 11:56 UTC, Wwwsylvia commented on Oras/Models/MemoryGraph.cs
> +    public class MemoryGraph
Can we move all everything related to Memory Target to `Oras/Memory` namespace?

2023-04-21 11:56 UTC, Wwwsylvia commented on Oras/Models/MinimumDescriptor.cs
> +    public class MinimumDescriptor
Let's keep it internal.

2023-04-21 11:56 UTC, Wwwsylvia commented on Oras/Models/Descriptor.cs
>      }
Can we move this part to `Oras/Content/Storage.cs`?

2023-04-21 11:59 UTC, sammychinedu2ky commented on Oras/Models/MinimumDescriptor.cs
> +    public class MinimumDescriptor
you mean public? cause you requested for a public change

2023-04-21 12:01 UTC, sammychinedu2ky commented on Oras/Constants/DockerMediaTypes.cs
> +       public const string ManifestList = "application/vnd.docker.distribution.manifest.list.v2+json";
I think it would be redundant, since DockerMediaTypes.ManifestList is still intuitive

2023-04-21 12:04 UTC, Wwwsylvia commented on Oras/Models/MemoryStorage.cs
> +    public class MemoryStorage : IStorage
Let's make `MemoryStorage` and `MemoryTagResolver` internal and keep `MemoryTarget` public.

2023-04-21 12:04 UTC, sammychinedu2ky commented on Oras/Constants/OCISPECMediaTypes.cs
> +    internal class OCISPECMediaTypes
I think differentiating between Docker Media Types and the OCISPECMediaTypes is needed

2023-04-24 09:53 UTC, sammychinedu2ky commented on Oras/Constants/DockerMediaTypes.cs
> +    internal class DockerMediaTypes
yep

2023-04-24 10:24 UTC, sammychinedu2ky commented on Oras/Models/Artifact.cs
> +    public class Artifact
should I also remove the reference here ?
https://github.com/oras-project/oras-dotnet/blob/935dc83bb422eeaf43bbce5401b2eb8c23e8b99d/Oras/Models/Descriptor.cs#L91-L95

2023-04-24 11:54 UTC, Wwwsylvia commented on Oras/Models/Artifact.cs
> +    public class Artifact
Yes let's remove everything related to `Subject`.

2023-04-24 12:24 UTC, Wwwsylvia requested changes
Unit tests are necessary

2023-04-24 12:24 UTC, Wwwsylvia commented on Oras/Memory/MemoryTarget.cs
> +    public class MemoryTarget : ITarget
Not sure if we want to call it `class MemoryTarget` or `class Target`.

2023-04-24 12:24 UTC, Wwwsylvia commented on Oras/Memory/MemoryStorage.cs
> +        private ConcurrentDictionary<MinimumDescriptor, byte[]> content { get; set; } = new ConcurrentDictionary<MinimumDescriptor, byte[]>();
Should the private member be named as `_content`?

2023-04-24 12:24 UTC, Wwwsylvia commented on Oras/Memory/MemoryStorage.cs
> +            if (!contentExist)
Do you mean
```suggestion
            if (contentExist)
```
?

2023-04-24 12:24 UTC, Wwwsylvia commented on Oras/Memory/MemoryStorage.cs
> +                var exists = content.TryAdd(key, memoryStream.ToArray());
Should this be called `added`?

2023-04-24 12:24 UTC, Wwwsylvia commented on Oras/Memory/MemoryTagResolver.cs
> +        private ConcurrentDictionary<string, Descriptor> index = new ConcurrentDictionary<string, Descriptor>();
`_index`?

2023-04-24 12:24 UTC, Wwwsylvia commented on Oras/Memory/MemoryTagResolver.cs
> +                throw new AlreadyExistsException();
NotFoundException?

2023-04-24 13:38 UTC, sammychinedu2ky commented on Oras/Content/Storage.cs
> +            // ought to implement a readall function to handle verification of the stream
yh

2023-04-24 14:00 UTC, sammychinedu2ky commented on Oras/Content/Storage.cs
> +    internal class Storage
I think that would be better. since it is a utility

2023-04-24 14:02 UTC, sammychinedu2ky commented on Oras/Memory/MemoryStorage.cs
> +        private ConcurrentDictionary<MinimumDescriptor, byte[]> content { get; set; } = new ConcurrentDictionary<MinimumDescriptor, byte[]>();
okay

2023-04-24 14:05 UTC, sammychinedu2ky commented on Oras/Memory/MemoryStorage.cs
> +                var exists = content.TryAdd(key, memoryStream.ToArray());
What do you mean?

2023-04-25 03:08 UTC, Wwwsylvia commented on Oras/Memory/MemoryStorage.cs
> +                var exists = content.TryAdd(key, memoryStream.ToArray());
I mean the return value of `TryAdd` should be called `added`. https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.tryadd?view=net-7.0#returns

2023-04-25 03:32 UTC, sammychinedu2ky commented on Oras/Memory/MemoryStorage.cs
> +                var exists = content.TryAdd(key, memoryStream.ToArray());
ok yh that's right

2023-04-25 03:59 UTC, Wwwsylvia requested changes

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Constants/OCIMediaTypes .cs
> +    }
The artifact media type can be removed.

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Interfaces/IFetcher.cs
> +        /// FetchAsync fetches the _content identified by the descriptor.
```suggestion
        /// FetchAsync fetches the content identified by the descriptor.
```

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Interfaces/IReadOnlyStorage.cs
> +    /// IReadOnlyStorage represents a read-only StorageUtility.
```suggestion
    /// IReadOnlyStorage represents a read-only Storage.
```

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Interfaces/IReadOnlyStorage.cs
> +        /// ExistsAsync returns true if the described _content exists.
Please check the misused `_content` in other places.

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Interfaces/IStorage.cs
> +    /// The _storage is designed to handle blobs of large sizes.
```suggestion
    /// The storage is designed to handle blobs of large sizes.
```

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +}
Can this part be introduced in another PR and be put in `Oras/Copy.cs`?

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +        public static async Task<IList<Descriptor>> SuccessorsAsync(IFetcher fetcher, Descriptor node, CancellationToken cancellationToken)
nit: I think an empty line is needed here.

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +        static async Task<Byte[]> FetchAllAsync(IFetcher fetcher, Descriptor desc, CancellationToken cancellationToken)
public?

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +            var t = await fetcher.FetchAsync(desc, cancellationToken);
nit: Why is this called `t`?

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +            var content = await StorageUtility.FetchAllAsync(fetcher, node, cancellationToken);
We don't need to fetch the content if the node's media type is not in the list. See https://github.com/oras-project/oras-go/blob/v2.0.2/content/graph.go#L47-L106

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +                        var descriptors = new List<Descriptor> { dockerManifest.Config }.Concat(dockerManifest.Layers).ToList();
I noticed that you use `Add` and `AddRange` in below but use `.Concat().ToList()` here. I'd like to learn which is more efficient?

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +            var tempByte = new byte[t.Length];
nit: maybe `bytes`?

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +}
Please introduce the Copy feature in a separate PR.

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +        public static async Task<IList<Descriptor>> SuccessorsAsync(IFetcher fetcher, Descriptor node, CancellationToken cancellationToken)
I just realized that the `Successors` method was originally defined in `conent/graph.go`. It may not be appropriate to put it in `StorageUtility.cs`. I'm still wondering how we should migrate the go-style structure to C#-style structure.

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Memory/MemoryStorage.cs
> +                throw new Exception($"{expected.Digest} : {expected.MediaType} : {new AlreadyExistsException().Message}");
Should this be 
```suggestion
                throw new AlreadyExistsException($"{expected.Digest} : {expected.MediaType}");
```
?

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Memory/MemoryTagResolver.cs
> +            _index.TryAdd(reference, descriptor);
What if the key (reference) already exists? 
The expected behavior is that the value to the key should be updated to the new descriptor.

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Memory/MemoryGraph.cs
> +        private ConcurrentDictionary<MinimumDescriptor, object> indexed = new ConcurrentDictionary<MinimumDescriptor, object>();
Do we need this? it looks like it's not used anywhere.

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Memory/MemoryGraph.cs
> +        private ConcurrentDictionary<MinimumDescriptor, ConcurrentDictionary<MinimumDescriptor, Descriptor>> predecessors = new ConcurrentDictionary<MinimumDescriptor, ConcurrentDictionary<MinimumDes
`_predecessors`?

2023-04-25 03:59 UTC, Wwwsylvia commented on Oras/Memory/MemoryTarget.cs
> +            await _tagResolver.TagAsync(descriptor, reference, cancellationToken);
Should we check the returned `exists` instead of catching the exception?

2023-04-25 04:00 UTC, Wwwsylvia commented
Please add some basic unit tests at least for `MemoryTarget` to verify the code works as expected.

2023-04-25 04:20 UTC, sammychinedu2ky commented on Oras/Memory/MemoryGraph.cs
> +        private ConcurrentDictionary<MinimumDescriptor, object> indexed = new ConcurrentDictionary<MinimumDescriptor, object>();
I might need it later

2023-04-26 05:20 UTC, Wwwsylvia commented on Test/OrasTest.csproj
Should we name the test directory `Oras.Tests` instead of `Test`?

2023-04-26 05:20 UTC, Wwwsylvia commented on Oras/Memory/MemoryTarget.cs
> +
How about
```suggestion
if (!exists)
{
      throw new NotFoundException($"{descriptor.Digest} : {descriptor.MediaType}");
}
await _tagResolver.TagAsync(descriptor, reference, cancellationToken);

```

2023-04-26 05:41 UTC, sammychinedu2ky commented on Oras/Memory/MemoryTarget.cs
> +
yh that is actually a better way to avoid the else statement and make it more succinct

2023-04-26 05:43 UTC, sammychinedu2ky commented on Test/OrasTest.csproj
yup let me change that

2023-04-26 05:46 UTC, sammychinedu2ky commented on Test/OrasTest.csproj
It doesn't seem to be a good identifier since I used a different project for it

2023-04-26 05:46 UTC, sammychinedu2ky commented on Test/OrasTest.csproj
@Wwwsylvia

2023-04-26 07:21 UTC, Wwwsylvia commented on Test/OrasTest.csproj
I found this naming convention in the official doc: https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test?source=recommendations

2023-04-26 07:34 UTC, Wwwsylvia commented on Oras/Memory/MemoryGraph.cs
> +}
nit: Should we have an empty line at the end of file?

2023-04-26 07:37 UTC, sammychinedu2ky commented on Oras/Memory/MemoryGraph.cs
> +}
nope

2023-04-26 08:13 UTC, sammychinedu2ky commented on Oras/Content/StorageUtility.cs
> +                        var descriptors = new List<Descriptor> { dockerManifest.Config }.Concat(dockerManifest.Layers).ToList();
Add adds an element to a list while `Concat` adds an enumerable by spreading it. So different use cases.
I can add {2,3,4,5} to a list using Concat. but to use add I would have to call add for each element.

2023-04-26 08:29 UTC, sammychinedu2ky commented on Oras/Content/StorageUtility.cs
> +            var t = await fetcher.FetchAsync(desc, cancellationToken);
I have changed the name 😄

2023-04-26 14:05 UTC, Wwwsylvia reviewed
Please take care of the access scopes of functions.

2023-04-26 14:05 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +        public static string CalculateHash(byte[] content)
Unit tests required.

2023-04-26 14:05 UTC, Wwwsylvia commented on Oras.Tests/MemoryTest/MemoryTargetTest.cs
More unit tests needed.

2023-04-26 14:41 UTC, sammychinedu2ky commented on Oras/Memory/MemoryGraph.cs
> +            if (successors is null)
yep

2023-04-27 08:59 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +            return await ReadAllAsync(stream, desc);
How about merging `StorageUtility` and `GraphUtility` into `Content/Content.cs`?

2023-04-27 08:59 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +        public static string CalculateHash(byte[] content)
CalculateDigest?

2023-04-27 08:59 UTC, Wwwsylvia commented on Oras/Memory/MemoryGraph.cs
> +            return await Task.FromResult(res);
Does 
```go
var res = predecessors.Values.ToList();
```
work?

2023-04-27 08:59 UTC, Wwwsylvia commented on Oras/Memory/MemoryGraph.cs
> +        internal async Task<IList<Descriptor>> PredecessorsAsync(Descriptor node, CancellationToken cancellationToken)
Unit tests needed.

2023-04-27 09:13 UTC, Wwwsylvia commented on Oras/Content/GraphUtility.cs
> +    internal static class GraphUtility
public

2023-04-27 09:13 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +[assembly: InternalsVisibleTo("Oras.Tests")]
I think this can be set at the project level?

2023-04-27 09:13 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +    internal static class StorageUtility
public

2023-04-27 09:13 UTC, Wwwsylvia commented on Oras/Interfaces/IFetcher.cs
> +    interface IFetcher
public?

2023-04-27 09:13 UTC, Wwwsylvia commented on Oras/Interfaces/IReadOnlyStorage.cs
> +    interface IReadOnlyStorage : IFetcher
All interfaces should be public

2023-04-27 09:13 UTC, Wwwsylvia commented on Oras.Tests/MemoryTest/MemoryTargetTest.cs
> +            await Assert.ThrowsAnyAsync<Exception>(async () =>
Should we test a specific exception like `MismatchedDigestException`?

2023-04-27 09:13 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +                throw new InvalidDescriptorSizeException("this descriptor size is less than content size");
The descriptor is invalid. Just that the size does not match. Should come up with another Exception, or just throw the original exception.

2023-04-27 09:18 UTC, sammychinedu2ky commented on Oras.Tests/MemoryTest/MemoryTargetTest.cs
> +            await Assert.ThrowsAnyAsync<Exception>(async () =>
Ok

2023-04-27 09:24 UTC, sammychinedu2ky commented on Oras/Content/StorageUtility.cs
> +                throw new InvalidDescriptorSizeException("this descriptor size is less than content size");
let me throw the original one

2023-04-27 09:53 UTC, sammychinedu2ky commented on Oras/Memory/MemoryGraph.cs
> +            return await Task.FromResult(res);
yh it does

2023-04-27 10:10 UTC, Wwwsylvia commented on Oras/Content/StorageUtility.cs
> +            return await ReadAllAsync(stream, desc);
I just feel that `CalculateDigest` and `ReadAllAsync` are not quite related to Storage🤔

2023-04-27 10:15 UTC, sammychinedu2ky commented on Oras/Content/StorageUtility.cs
> +            return await ReadAllAsync(stream, desc);
I think the same. Putting all the methods in a single file might be okay

2023-04-28 02:49 UTC, Wwwsylvia commented on Oras/Models/MinimumDescriptor.cs
> +    public class MinimumDescriptor : IEquatable<MinimumDescriptor>
This should be internal.

2023-04-28 02:49 UTC, Wwwsylvia commented on Oras/Memory/MemoryGraph.cs
> +            if (successors is null)
Can we check if it's null or empty? It's currently checking null only.

2023-04-28 02:49 UTC, Wwwsylvia commented on Oras/Memory/MemoryGraph.cs
> +            var minimumDescriptor = Descriptor.FromOCI(node);
maybe call it `key`

2023-04-28 02:49 UTC, Wwwsylvia commented on Oras/Memory/MemoryGraph.cs
> +                return null;
Should we return `default` here?

2023-04-28 04:15 UTC, Wwwsylvia commented on Oras.Tests/MemoryTest/MemoryTargetTest.cs
> +              null!}; // blob 8
nit: can we format these?

2023-04-28 04:15 UTC, Wwwsylvia commented on Oras.Tests/MemoryTest/MemoryTargetTest.cs
> +}
nit: need an empty line here.

2023-04-28 04:24 UTC, sammychinedu2ky commented on Oras/Memory/MemoryGraph.cs
> +                return null;
yh

2023-04-28 04:24 UTC, sammychinedu2ky commented on Oras.Tests/MemoryTest/MemoryTargetTest.cs
> +              null!}; // blob 8
ok

2023-04-28 04:46 UTC, sammychinedu2ky commented on Oras/Memory/MemoryGraph.cs
> +            if (successors is null)
from my implementation. any empty list is null

2023-04-28 07:03 UTC, sammychinedu2ky commented
Here is the Code Coverage Report of the Test taken
![image](https://user-images.githubusercontent.com/36219292/235078023-822912ee-87ed-4c70-bf24-a6ba2b5fd547.png)

2023-04-28 07:05 UTC, Wwwsylvia approved these changes
LGTM

2023-04-28 07:06 UTC, merged