feat: Implement Pack Manifests
oras-project/oras-dotnet pull request #149
Opened 2024-10-17 17:56 UTC by nhu1997

### What this PR does / why we need it
There are use cases where .net sdk is needed to support attaching annotations such as End of Life.

### Which issue(s) this PR resolves / fixes
Pack Manifests · Issue #39 · oras-project/oras-dotnet (github.com)

### Please check the following list
- [x] Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [x] Does this change require a documentation update?
- [ ] Does this introduce breaking changes that would require an announcement or bumping the major version?
- [x] Do all new files have an appropriate license header?

2024-10-17 17:59 UTC, sajayantony commented
@nhu1997 could you fix the DCO errors?

2024-10-21 11:14 UTC, shizhMSFT requested changes

2024-10-21 11:14 UTC, shizhMSFT commented on src/OrasProject.Oras/Pack.cs
> +        if (string.IsNullOrEmpty(artifactType) && (options.Config == null || options.Config.MediaType == "application/vnd.oci.empty.v1+json"))
This comment also applies to other parts of this file.

2024-10-21 11:14 UTC, shizhMSFT commented on src/OrasProject.Oras/Pack.cs
> +        var annotations = EnsureAnnotationCreated(options.ManifestAnnotations, "org.opencontainers.image.created");
Should we have a class for common annotations?

2024-10-21 11:14 UTC, shizhMSFT commented on src/OrasProject.Oras/Pack.cs
> +        };
Should we add a constructor for `Descriptor` as a C# version of `content.NewDescriptorFromBytes`?

2024-10-21 11:14 UTC, shizhMSFT commented on src/OrasProject.Oras/Pack.cs
> +        if (annotations is null)
nit: I'm not which one is better (`is` or `==`).
```suggestion
        if (annotations == null)
```

2024-10-21 11:14 UTC, shizhMSFT commented on src/OrasProject.Oras/Pack.cs
> +        if (annotations.ContainsKey(key))
Instead of `ContainerKey` then `[]`, you may try `TryGetValue`.

2024-10-22 03:49 UTC, nhu1997 commented on src/OrasProject.Oras/Exceptions/InvalidPackException.cs
Yes, removed it

2024-10-22 03:49 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +	//     and PackManifestOptions.ConfigDescriptor is not specified.
Updated the comments

2024-10-22 03:49 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +	public const string MediaTypeUnknownArtifact = "application/vnd.unknown.artifact.v1";
Updated

2024-10-22 03:51 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +	public const string MediaTypeUnknownArtifact = "application/vnd.unknown.artifact.v1";
OrasProject.Oras.Oci.mediaType.cs exists already

2024-10-22 03:54 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +    public const string ErrMissingArtifactType = "missing artifact type";
they are error messages and are used in Exceptions. i.e:

if (!DateTime.TryParse(annotations[key], out _))
{
    throw new InvalidDateTimeFormatException(ErrInvalidDateTimeFormat);
}
and
if (string.IsNullOrEmpty(artifactType) && (options.Config == null || options.Config.MediaType == "application/vnd.oci.empty.v1+json"))
{
    throw new MissingArtifactTypeException(ErrMissingArtifactType);
}

2024-10-22 04:12 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +public static class Pack
Basically Pack class is to pack the manifest and push it to storage, it is not an extension of IPushable. Moreover, Pack class is more like an utility class which does not have its own properties, it is similar to extension.cs

2024-10-22 04:25 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +        [JsonPropertyName("mediaType")]
Actually, this field is not used at all, the reason it is here is to keep consistent with golang version api. Also, meida type format is json means the image manifest format, not PackManifestOptions format.

2024-10-22 04:30 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +        public List<Descriptor> Layers { get; set; }
Updated

2024-10-22 04:43 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +    public static async Task<Descriptor> PackManifest(
Updated

2024-10-22 04:45 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +            MediaType = "application/vnd.oci.image.manifest.v1+json",
Updated

2024-10-22 04:49 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +        if (string.IsNullOrEmpty(artifactType) && (options.Config == null || options.Config.MediaType == "application/vnd.oci.empty.v1+json"))
Updated

2024-10-22 04:51 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +		}
It is strange that the code style looks normal in visual studio

2024-10-22 11:18 UTC, Wwwsylvia commented on src/OrasProject.Oras/Pack.cs
> +	//     and PackManifestOptions.ConfigDescriptor is not specified.
Are the latest commits pushed?

2024-10-22 17:17 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +            };
Add a static Empty field in Descriptor

2024-10-22 17:53 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +        var annotations = EnsureAnnotationCreated(options.ManifestAnnotations, "org.opencontainers.image.created");
Not quite sure. Based on spec: it is an optional annotations property for certain components, which contains arbitrary metadata. It is just a key-value map and by default it is empty. When it associates with a component, i. e an image, then this map should have key-value: org.opencontainers.image.created - timestamp which image is created. So I am not sure a common annotaions is necessary

2024-10-22 18:28 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +        };
because MediaType and Digest are required members in Descriptor class, they must be set in the object initializer or attribute constructor. The current way is C# version of object initializer

2024-10-22 18:29 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +        if (annotations is null)
Updated

2024-10-22 18:34 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +        if (annotations.ContainsKey(key))
Here the logic is like this:
If annotations does not contain this key, a new copy annotations is created and add this key and current timestamp to the new annotations, then return.
otherwise the value of the key will be check, if its format is wrong, an exception will be thrown.  if the format is correct, the original annotations returns.

If we TryGetValue, we still have to check the value is null or its format if it is not null. From code point of view, no any optimization and even one more line code, we have to define a out string as parameter in TryGetValue

2024-10-22 18:38 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +        [JsonPropertyName("mediaType")]
right, remove the annotations.

2024-10-23 04:11 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +	//     and PackManifestOptions.ConfigDescriptor is not specified.
Yes.

2024-10-23 04:19 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +    public struct PackManifestOptions
done

2024-10-29 09:25 UTC, shizhMSFT commented on src/OrasProject.Oras/PackManifestOptions.cs
> +namespace OrasProject.Oras.Oci;
```suggestion
namespace OrasProject.Oras;
```

2024-10-29 09:25 UTC, shizhMSFT commented on src/OrasProject.Oras/Pack.cs
> +    public const string ErrMissingArtifactType = "missing artifact type";
Based on https://github.com/oras-project/oras-dotnet/pull/149#discussion_r1809812828, should them be `private`?

2024-10-29 09:25 UTC, shizhMSFT commented on src/OrasProject.Oras/Pack.cs
> +            PackManifestOptions options,
nit: will this work?
```suggestion
            PackManifestOptions options = default,

```

2024-10-29 09:25 UTC, shizhMSFT commented on src/OrasProject.Oras/Pack.cs
> +            ITarget pusher,
Does it require `ITarget` or `IPushable`?

2024-10-29 09:25 UTC, shizhMSFT commented on src/OrasProject.Oras/Pack.cs
> +            var expectedConfigBytes = Encoding.UTF8.GetBytes("{}");
It seems not used anywhere.

2024-10-29 09:25 UTC, shizhMSFT commented on src/OrasProject.Oras/Pack.cs
> +        };
I'm wondering if we can have something like
```csharp
public Descriptor(string mediaType, byte[] content)
```

2024-10-29 09:25 UTC, shizhMSFT commented on src/OrasProject.Oras/Pack.cs
> +            var configBytes = JsonSerializer.SerializeToUtf8Bytes(new { });
Should it just be
```suggestion
            var configBytes = new byte[] { 0x7B, 0x7D };

```

2024-10-29 09:26 UTC, shizhMSFT commented on src/OrasProject.Oras/Pack.cs
> +            var configBytes = JsonSerializer.SerializeToUtf8Bytes(new { });
or
```suggestion
            var configBytes = configDescriptor.Data;

```

2024-10-30 03:56 UTC, nhu1997 commented on src/OrasProject.Oras/Oci/Descriptor.cs
Changed to LF

2024-10-30 03:57 UTC, nhu1997 commented on src/OrasProject.Oras/Oci/Descriptor.cs
> +    internal static Descriptor Empty => new Descriptor
Changed

2024-10-30 04:01 UTC, nhu1997 commented on src/OrasProject.Oras/Oci/Descriptor.cs
> +        Data = Encoding.UTF8.GetBytes("{}")
replaced with pre-computed values

2024-10-30 04:23 UTC, nhu1997 commented on src/OrasProject.Oras/Oci/MediaType.cs
> +    public const string MediaTypeUnknownArtifact = "application/vnd.unknown.artifact.v1";
Created a UnknownMediaType class and move these two strings there

2024-10-30 04:24 UTC, nhu1997 commented on src/OrasProject.Oras/PackManifestOptions.cs
> +namespace OrasProject.Oras.Oci;
Thanks, did not notice that.

2024-10-30 04:31 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +    public const string ErrMissingArtifactType = "missing artifact type";
changed to private const string _errorMissingArtifactType  and private const string _errorInvalidDateTimeFormat

2024-10-30 05:48 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +            PackManifestOptions options,
yes, changed

2024-10-30 05:55 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +            ITarget pusher,
Changed

2024-10-30 05:56 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +            var expectedConfigBytes = Encoding.UTF8.GetBytes("{}");
removed

2024-10-30 06:00 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +            var configBytes = JsonSerializer.SerializeToUtf8Bytes(new { });
changed

2024-10-31 03:26 UTC, nhu1997 commented on src/OrasProject.Oras/Pack.cs
> +        };
In order to support both, I added default construct and attribute construct:

public Descriptor()
{
}

public Descriptor(string mediaType, string digest)
{
    MediaType = mediaType;
    Digest = digest;
}

2024-11-07 01:20 UTC, shizhMSFT commented on src/OrasProject.Oras/Oci/Descriptor.cs
> +        (MediaType, Digest) = (mediaType, digest);
It may be better to have a function to generate a descriptor form a byte array or in general `Span<byte>`.

2024-11-07 01:20 UTC, shizhMSFT commented on src/OrasProject.Oras/Oci/Descriptor.cs
> +        Data = Encoding.UTF8.GetBytes("{}")
```suggestion
        Data = new byte[] { 0x7B, 0x7D }
```

2024-11-07 01:20 UTC, shizhMSFT commented on src/OrasProject.Oras/Pack.cs
> +        PackManifestVersion1_0 = 1,
It will look like `Pack.PackManifestVersion.PackManifestVersion1_0`.

2024-11-07 01:20 UTC, shizhMSFT commented on src/OrasProject.Oras/Pack.cs
> +public static class Pack
Is it better to name it as `Packer`?

2024-11-07 01:20 UTC, shizhMSFT commented on src/OrasProject.Oras/UnknownMediaType.cs
> +public static class UnknownMediaType
```suggestion
public static class MediaType
```

2024-11-10 06:01 UTC, nhu1997 commented on src/OrasProject.Oras/Oci/Descriptor.cs
> +        (MediaType, Digest) = (mediaType, digest);
Add a method Create()

2024-11-11 15:54 UTC, shizhMSFT commented on src/OrasProject.Oras/Oci/Descriptor.cs
> +            Data = byteData,
The `Create()` function should not have the `Data` field for the `Descriptor`. The `Data` field is used only for special cases and expected to be small.

2024-11-11 15:54 UTC, shizhMSFT commented on src/OrasProject.Oras/Oci/Descriptor.cs
> +    public static Descriptor Empty => Descriptor.Create(new byte[] { 0x7B, 0x7D }, OrasProject.Oras.Oci.MediaType.EmptyJson);
Agreed. Should revert to the previous version.

We should consider basic level of performance improvement to avoid wasting unnecessary computing power which can be easily picked up.

2024-11-11 15:54 UTC, shizhMSFT commented on src/OrasProject.Oras/Utils/MediaType.cs
> +namespace OrasProject.Oras.Utils;
Shouldn't it just be 
```suggestion
namespace OrasProject.Oras;
```
Avoid using any `Utils` namespaces in a library. Anything in the `Utils` should be placed in a right place.

2024-11-12 06:08 UTC, nhu1997 commented on src/OrasProject.Oras/Oci/Descriptor.cs
> +    public static Descriptor Empty => Descriptor.Create(new byte[] { 0x7B, 0x7D }, OrasProject.Oras.Oci.MediaType.EmptyJson);
reverted.

2024-11-12 06:38 UTC, shizhMSFT commented on src/OrasProject.Oras/Packer.cs
> +    public const string UnknownArtifact = "application/vnd.unknown.artifact.v1";
Should we add a `MediaType` prefix?

2024-11-12 06:54 UTC, shizhMSFT approved these changes
LGTM

2024-11-12 06:57 UTC, merged