feat: Implemented CopyGraph
oras-project/oras-dotnet pull request #15
Opened 2023-04-25 11:23 UTC by sammychinedu2ky

Fixes https://github.com/oras-project/oras-dotnet/issues/5

2023-04-26 08:13 UTC, Wwwsylvia requested changes

2023-04-26 08:13 UTC, Wwwsylvia commented on Oras/Oras.cs
> +            if (await dst.ExistsAsync(node, cancellationToken))
Why do we need to copy when the content exists in dst?

2023-04-26 08:13 UTC, Wwwsylvia commented on Oras/Oras.cs
> +                var dataStream = new MemoryStream(await StorageUtility.FetchAllAsync(src, node, cancellationToken));
Can we just use `src.FetchAsync`?

2023-04-26 08:13 UTC, Wwwsylvia commented on Oras/Oras.cs
> +                var childNodes = await StorageUtility.SuccessorsAsync(src, node, cancellationToken);
Note that `SuccessorAsync` internally calls `FetchAsync`. Which means a node will actually be fetched multiple times in the current implementation.

2023-04-26 08:13 UTC, Wwwsylvia commented on Oras/Oras.cs
> +        private async Task CopyGraphAsync(ITarget src, ITarget dst, Descriptor node, CancellationToken cancellationToken)
This function should be public.

2023-04-26 14:13 UTC, Wwwsylvia requested changes

2023-04-26 14:13 UTC, Wwwsylvia commented on Oras/Copy.cs
> +        public async Task<Descriptor> CopyAsync(ITarget src, string srcRef, ITarget dst, string dstRef, CancellationToken cancellationToken)
Should this be a static method?

2023-04-26 14:13 UTC, Wwwsylvia commented on Oras/Copy.cs
> +        // Returns the descriptor of the root node on successful copy.
These are not C# style comment docs.

2023-04-26 14:13 UTC, Wwwsylvia commented on Oras/Copy.cs
> +                var childNodes = await StorageUtility.SuccessorsAsync(src, node, cancellationToken);
Why not just call it `successors`?

2023-04-26 14:13 UTC, Wwwsylvia commented on Oras/Copy.cs
> +        }
Can we rewrite this method in an iterative (non-recursive) style?

2023-04-28 04:26 UTC, Wwwsylvia commented on Oras/Copy.cs
> +        }
How about 
```suggestion
                if (successors != null)
                {
                    foreach (var childNode in successors)
                    {
                        await CopyGraphAsync(src, dst, childNode, cancellationToken);
                    }
                }
                await dst.PushAsync(node, dataStream, cancellationToken);
            }
        }
```

2023-04-28 04:56 UTC, sammychinedu2ky commented on Oras/Copy.cs
> +        }
yh that's right

2023-04-28 07:19 UTC, closed without merging