chore: update README.md
oras-project/oras-dotnet pull request #2
Opened 2023-03-15 15:26 UTC by shizhMSFT

Update `README.md` for reviewing guide and code of conduct.

Partially resolves the issue https://github.com/oras-project/community/issues/38

2023-03-15 15:29 UTC, sammychinedu2ky approved these changes

2023-03-15 16:05 UTC, TerryHowe requested changes

2023-03-15 16:05 UTC, TerryHowe commented on README.md
> +> **Warning** This project is currently under active development. The API may and will change incompatibly from one commit to another.
To me, active development is the desired state of any project. Maybe "alpha development" or "initial development"

```suggestion
> **Warning** This project is currently under initial development. The API may and will be incompatibly from one commit to another.
```

2023-03-15 16:09 UTC, SteveLasker commented on README.md
> +> **Warning** This project is currently under active development. The API may and will change incompatibly from one commit to another.
@shizhMSFT, can we add some text that describes the scope of this repo/sub-project?

2023-03-16 01:16 UTC, sajayantony approved these changes

2023-03-16 01:22 UTC, TerryHowe approved these changes

2023-03-16 01:25 UTC, SteveLasker commented on README.md
> +> **Warning** This project is currently under active development. The API may and will change incompatibly from one commit to another.
The question about scope of each sub-project continues to come up. I'm suggesting the readme can define the scope:
"The oras-dotnet repo is scoped at implementing a dotnet version of ORAS functionality. "

The interesting thing that came up with the oras-py implementation is whether each library is following an implementation of a common spec? What's the reference for each library? 
For now, It's probably ok to just say the above.

2023-03-16 01:26 UTC, sabre1041 approved these changes
LGTM

2023-03-16 02:46 UTC, Wwwsylvia approved these changes
LGTM

2023-03-16 02:48 UTC, sammychinedu2ky approved these changes

2023-03-16 03:24 UTC, shizhMSFT commented on README.md
> +> **Warning** This project is currently under active development. The API may and will change incompatibly from one commit to another.
@SteveLasker I've created the following issue
- https://github.com/oras-project/community/issues/46

to discuss your concerns.

2023-03-16 03:26 UTC, merged

2023-03-16 03:26 UTC, shizhMSFT commented
Merging this PR as it got approved by a majority of org-level maintainers and all conversations are resolved.