feat: Added IRepository
oras-project/oras-dotnet pull request #20
Opened 2023-05-02 04:44 UTC by sammychinedu2ky

fixes https://github.com/oras-project/oras-dotnet/issues/17

2023-05-04 04:04 UTC, Wwwsylvia requested changes

2023-05-04 04:04 UTC, Wwwsylvia commented on Oras/Interfaces/IDeleter.cs
> +    internal interface IDeleter
public

2023-05-04 04:04 UTC, Wwwsylvia commented on Oras/Interfaces/IBlobTarget.cs
> +    internal interface IBlobTarget : ITarget, IResolver, IDeleter, IReferenceFetcher
`BlobStore`?  See https://github.com/oras-project/oras-go/blob/v2.0.2/registry/repository.go#L56-L62. Note that it should not implement `ITarget`.

2023-05-04 04:04 UTC, Wwwsylvia commented on Oras/Interfaces/IManifestTarget.cs
> +    internal interface IManifestTarget : IBlobTarget, IReferencePusher, ITag
`IManifestStore`?

2023-05-04 04:04 UTC, Wwwsylvia commented on Oras/Interfaces/IRepository.cs
> +    internal interface IRepository : ITarget, ITagResolver, IReferenceFetcher, IReferencePusher, IReferrerLister, IDeleter
`ITarget` already implies `ITagResolver`, so `ITagResolver` is redundant here.

2023-05-04 07:14 UTC, sammychinedu2ky commented on Oras/Interfaces/ITagLister.cs
> +        Task TagsAsync(string last, Func<string[], Task> fn);
Yh you're right

2023-05-04 07:28 UTC, sammychinedu2ky commented on Oras/Interfaces/IReferenceFetcher.cs
I think that would be okay for easier identification and accessibility

2023-05-04 07:48 UTC, sammychinedu2ky commented on Oras/Interfaces/ITag.cs
> +    public interface ITag
Anyone is okay, but let me conform to the golang code style

2023-05-05 06:36 UTC, shizhMSFT commented on Oras/Interfaces/Registry/IReferenceFetcher.cs
> +        (Task<Descriptor>, Task<Stream>) FetchReferenceAsync(string reference, CancellationToken cancellationToken = default);
Question for you: How do you invoke this method?

2023-05-05 06:36 UTC, shizhMSFT commented on Oras/Interfaces/Registry/IReferenceFetcher.cs
> +        (Task<Descriptor>, Task<Stream>) FetchReferenceAsync(string reference, CancellationToken cancellationToken = default);
You have multiple options:

Option 1:
```csharp
Task<(Descriptor, Stream)> FetchReferenceAsync(string reference, CancellationToken cancellationToken = default);
```

Option 2:
```csharp
Task<Descriptor> FetchReferenceAsync(string reference, out Steam steam CancellationToken cancellationToken = default);
```

Option 3:
```csharp
Task<Stream> FetchReferenceAsync(string reference, out Descriptor descriptor, CancellationToken cancellationToken = default);
```

2023-05-08 06:14 UTC, Wwwsylvia requested changes

2023-05-08 06:14 UTC, Wwwsylvia commented on Oras/Interfaces/Registry/ITagLister.cs
> +        /// of the Tags list.
nit: Should we move the descriptor for the parameters into <param>s?

2023-05-08 06:34 UTC, Wwwsylvia commented on Oras/Interfaces/Registry/IDeleter.cs
> +    public interface IDeleter
`IDeleter` should not be under the registry namespace.

2023-05-08 08:08 UTC, Wwwsylvia commented on Oras/Interfaces/Registry/IRepository.cs
> +    /// assume that content.Resolver interface only works for manifests. Tagging a
nit: 
```suggestion
    /// assume that IResolver interface only works for manifests. Tagging a
```

2023-05-08 08:08 UTC, Wwwsylvia commented on Oras/Interfaces/Registry/IRepository.cs
> +    /// blob may be resulted in an `ErrUnsupported` error. However, this interface
There is no `ErrUnsupported` error in the oras-dotnet.

2023-05-08 08:08 UTC, Wwwsylvia commented on Oras/Interfaces/Registry/IRepository.cs
> +    /// operations defined in the `BlobStore` are executed depending on the media
IBlobStore? Please review other comments for similar issues.

2023-05-08 10:28 UTC, Wwwsylvia approved these changes
LGTM

2023-05-08 11:10 UTC, merged