feat: Registry
oras-project/oras-dotnet pull request #21
Opened 2023-05-18 06:56 UTC by sammychinedu2ky

fixes https://github.com/oras-project/oras-dotnet/issues/18

2023-05-22 07:01 UTC, Wwwsylvia requested changes

2023-05-23 05:09 UTC, Wwwsylvia requested changes

2023-05-23 05:09 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            {
Will `MediaTypeHeaderValue.TryParse()` throw any exception? Should we check the return value instead? See https://learn.microsoft.com/en-us/dotnet/api/microsoft.net.http.headers.mediatypeheadervalue.tryparse?view=aspnetcore-7.0

2023-05-23 05:09 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            catch (Exception e)
nit: `e` is never used.

2023-05-23 05:09 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            res.Content.Headers.TryGetValues("Docker-Content-Digest", out var serverHeaderDigest);
Should we chec the return value?

2023-05-23 05:09 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            if (serverHeaderDigest.FirstOrDefault().Length == 0)
`serverHeaderDigest.FirstOrDefault()` is called multiple times. Can we call it outside?
BTW, should we use `string.IsNullOrEmpty` ?

2023-05-23 05:09 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +                    if (refDigest.Length == 0)
Same here

2023-05-23 05:09 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +                contentDigest = serverHeaderDigest.FirstOrDefault();
This line should be put outside of the if/else statement so that it can be used in anywhere. Otherwise `FirstOrDefault` will be called multiple times.

2023-05-23 11:41 UTC, Wwwsylvia requested changes
Should we wrap the usage of `Stream` and other `IDisposable` with `using` statement?

2023-05-23 11:41 UTC, Wwwsylvia commented on Oras/Remote/Utils.cs
> +        public static byte[] LimitReader(HttpContent content, long n)
The behavior of this function does not match the description. It does not stop after n bytes.

2023-05-23 11:41 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +        private async Task deleteWithIndexingAsync(Descriptor target, CancellationToken cancellationToken)
Same here. This function is unnecessary, and we can directly call `DoDeleteAsync` in `DeleteAsync`

2023-05-23 11:41 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +                    if (resp.Content.Headers.ContentLength == -1)
This logic is different with line 742. Which one is correct?

2023-05-23 11:41 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            catch (Exception ex) when (ex is NotFoundException)
Curious that should we just catch `NotFoundException`?

2023-05-23 11:41 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            string location = String.Empty;
nit: you may not need to initialize this value.

2023-05-23 11:41 UTC, Wwwsylvia requested changes
Should we wrap the usage of `Stream` and other `IDisposable` with `using` statement?

2023-05-25 02:08 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +        internal async Task deleteAsync(Descriptor target, bool isManifest, CancellationToken cancellationToken)
I used it in a test 😄. So internal is okay

2023-05-25 02:08 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +        internal async Task deleteAsync(Descriptor target, bool isManifest, CancellationToken cancellationToken)
DeleteAsync is okay, use of prefixes for methods is not a common convention in C#

2023-05-25 02:10 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +    public class RepositoryOption : IRepositoryOption
yh in test

2023-05-25 02:11 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +                    throw new InvalidReferenceException();
not really

2023-05-25 02:12 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +                client.DefaultRequestHeaders.Add("User-Agent", new string[] { "oras-dotnet" });
that is what the repository option is for.
also it could be set directly on the object

2023-05-25 02:15 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +    public class ManifestStore : IManifestStore
internal

2023-05-25 02:26 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +            await pushWithIndexing(expected, content, expected.Digest, cancellationToken);
ok

2023-05-25 02:51 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +            res.Content.Headers.TryGetValues("Docker-Content-Digest", out var serverHeaderDigest);
I did below

2023-05-25 03:17 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +            refObj.Reference = target.Digest;
yh to prevent unnecessary computation

2023-05-25 03:30 UTC, sammychinedu2ky commented on Oras/Models/Descriptor.cs
> +        }
I think by convention this is acceptable. What do you think?

2023-05-25 10:15 UTC, Wwwsylvia requested changes

2023-05-25 10:15 UTC, Wwwsylvia commented on Oras/Remote/Utils.cs
> +            var link = String.Empty;
nit:
```suggestion
            string link;
```
?

2023-05-25 10:15 UTC, Wwwsylvia commented on Oras/Remote/Utils.cs
> +            if (link.IndexOf('>') is var index && index < -1)
Do you mean `index == -1`?

2023-05-25 14:04 UTC, sammychinedu2ky commented on Oras/Remote/Reference.cs
> +            string reference = String.Empty;
would cause an error because it is needed somewhere as an initialized string

2023-05-25 14:29 UTC, sammychinedu2ky commented on Oras/Remote/Registry.cs
> +}
it is already the object I am instantiating

2023-05-26 05:00 UTC, Wwwsylvia commented on Oras/Remote/Registry.cs
> +}
Sorry what do you mean? I don't get it.

2023-05-26 05:12 UTC, Wwwsylvia commented on Oras/Remote/Registry.cs
> +    public class Registry : IRepositoryOption
Just realized that there is an interface for Registry: https://github.com/oras-project/oras-go/blob/v2.2.0/registry/registry.go#L22

2023-05-26 05:12 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +
Let's remove this.

2023-05-26 05:12 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +        public Repository(RemoteReference @ref, IRepositoryOption option)
Should this be internal? See https://github.com/oras-project/oras-go/blob/v2.2.0/registry/remote/repository.go#L140.

BTW, let's avoid using `@ref` as the argument name, and use `reference` or `remoteReference` instead.

2023-05-26 05:12 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +                    throw new InvalidReferenceException();
I mean this logic should be reached for both `try` and `catch` cases. See https://github.com/oras-project/oras-go/blob/v2.2.0/registry/remote/repository.go#L309-L311

2023-05-26 05:12 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            {
I mean we can still use `TryParse`, but we should check its return value.

2023-05-26 05:12 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            res.Content.Headers.TryGetValues("Docker-Content-Digest", out var serverHeaderDigest);
I mean the return value of `TryGetValues`. This function returns a bool.

2023-05-26 07:39 UTC, Wwwsylvia requested changes

2023-05-26 07:39 UTC, Wwwsylvia commented on Oras/Remote/Reference.cs
> +}
This looks redundant.

2023-05-26 07:39 UTC, Wwwsylvia commented on Oras/Remote/Registry.cs
> +    public class Registry : IRegistry
```suggestion
    public class Registry : IRegistry, IRepositoryOption
```
?

2023-05-26 07:39 UTC, Wwwsylvia commented on Oras/Remote/Registry.cs
> +                var client = new HttpClient();
This line of code creates a new `HttpClient` instance everytime. We should use a singleton instead.

2023-05-26 07:39 UTC, Wwwsylvia commented on Oras/Remote/Registry.cs
> +                var client = new HttpClient();
For simplicity, I think we can just move this into the constructor.

2023-05-26 07:39 UTC, Wwwsylvia commented on Oras/Remote/Registry.cs
> +            }
Why do we need these? Didn't we handle the http/https scheme in `BuildRegistryCatalogURL` already?

2023-05-26 07:39 UTC, Wwwsylvia commented on Oras/Remote/Registry.cs
> +                if (last != "")
`string.IsNullOrEmpty`?

2023-05-26 07:39 UTC, Wwwsylvia commented on Oras/Remote/Registry.cs
> +            var response = await HttpClient.GetAsync(uriBuilder.ToString(), cancellationToken);
Should we put a `using` keyword here? See https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-7.0#examples
Same for other HTTP responses.

2023-05-26 07:39 UTC, Wwwsylvia commented on Oras.Tests/RemoteTest/RegistryTest.cs
> +            };
The test data is not correct. The response body should be formatted as a JSON string. See https://docs.docker.com/registry/spec/api/#listing-repositories

```JSON
{
  "repositories": [
    <name>,
    ...
  ]
}
```

2023-05-26 07:39 UTC, Wwwsylvia commented on Oras.Tests/RemoteTest/RemoteTest.cs
> +    public class RemoteTest
Should we call this `RepositoryTest`?

2023-05-26 07:39 UTC, Wwwsylvia commented on Oras/Remote/Registry.cs
> +            var repositories = JsonSerializer.Deserialize<string[]>(data);
We need to deserialize it from the "repositories" object. See https://docs.docker.com/registry/spec/api/#listing-repositories

2023-05-26 09:15 UTC, Wwwsylvia requested changes

2023-05-26 09:15 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            if (refDigest.Length > 0 && refDigest != contentDigest)
nit: `!string.IsNullOrEmpty()`?

2023-05-26 09:15 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +        private async Task<string> CalculateDigestFromResponse(HttpResponseMessage res)
static?

2023-05-26 09:15 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            DigestUtility.Parse(target.Digest);
I realized that this might not be necessary if we don't verify the content digest

2023-05-26 09:15 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            url = location;
Maybe let's remove this for simplicity

2023-05-26 09:15 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            {
This is not needed.

2023-05-26 09:15 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            req.RequestUri = new Uri($"{req.RequestUri}?digest={expected.Digest}");
Should we use `UriBuilder` like we do in other places?

2023-05-26 17:37 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +        private async Task<string> CalculateDigestFromResponse(HttpResponseMessage res)
nah. it is only used in this class

2023-05-27 12:35 UTC, Wwwsylvia commented on Oras.Tests/CopyFromRepositoryToMemory.cs
> +    public class CopyFromRepositoryToMemory
Please move it to `RepositoryTest`

2023-05-27 12:35 UTC, Wwwsylvia commented on Oras.Tests/CopyFromRepositoryToMemory.cs
> +        public async Task Test_CopyFromRepositoryToMemory()
Please the test case to `RepositoryTest.cs`

2023-05-27 12:57 UTC, Wwwsylvia commented on Oras/Content/DigestUtility.cs
> +                throw new InvalidReferenceException($"Invalid digest: {digest}");
nit: InvalidDigestException

2023-05-27 13:02 UTC, Wwwsylvia commented on Oras/Remote/LinkUtils.cs
> +
What if `link` is an absolute URL already?

2023-05-27 13:02 UTC, Wwwsylvia commented on Oras/Remote/LinkUtils.cs
> +    internal class LinkUtils
nit: LinkUtility?

2023-05-27 13:02 UTC, Wwwsylvia commented on Oras/Remote/LinkUtils.cs
> +        internal static string ObtainUrl(string url, bool plainHttp)
I still don't get why do we need this

2023-05-27 13:05 UTC, sammychinedu2ky commented on Oras/Remote/LinkUtils.cs
> +
that's true

2023-05-27 13:06 UTC, Wwwsylvia commented on Oras/Remote/RemoteReference.cs
> +        private static string repositoryRegexp = @"^[a-z0-9]+(?:(?:[._]|__|[-]*)[a-z0-9]+)*(?:/[a-z0-9]+(?:(?:[._]|__|[-]*)[a-z0-9]+)*)*$";
const

2023-05-27 13:06 UTC, Wwwsylvia commented on Oras/Remote/RemoteReference.cs
> +        private static string tagRegexp = @"^[\w][\w.-]{0,127}$";
same here

2023-05-27 13:06 UTC, Wwwsylvia commented on Oras/Remote/ResponseTypes.cs
> +}
Just a question, can these be structs?

2023-05-27 13:06 UTC, sammychinedu2ky commented on Oras/Remote/LinkUtils.cs
> +
looked at the full code. It would still be sticked together.

2023-05-27 13:07 UTC, sammychinedu2ky commented on Oras/Remote/LinkUtils.cs
> +        internal static string ObtainUrl(string url, bool plainHttp)
some location headers are relative and some are not

2023-05-27 13:11 UTC, Wwwsylvia commented on Oras/Remote/LinkUtils.cs
> +        internal static string ObtainUrl(string url, bool plainHttp)
But you have handled the scheme in `ParseLink`?

2023-05-27 13:11 UTC, sammychinedu2ky commented on Oras/Remote/ResponseTypes.cs
> +}
yh

2023-05-27 13:12 UTC, Wwwsylvia commented on Oras/Content/DigestUtility.cs
> +        private static string digestRegexp = @"[a-z0-9]+(?:[.+_-][a-z0-9]+)*:[a-zA-Z0-9=_-]+";
const

2023-05-27 13:22 UTC, Wwwsylvia commented on Oras/Remote/Registry.cs
> +    public class Registry : IRegistry
```suggestion
    public class Registry : IRegistry, IRepositoryOption
```

2023-05-27 13:22 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +    public class Repository : IRepository
```suggestion
    public class Repository : IRepository, IRepositoryOption
```

2023-05-27 13:22 UTC, Wwwsylvia commented on Oras/Interfaces/Registry/IRepositoryOption.cs
> +    public interface IRepositoryOption
This is not used anywhere

2023-05-27 13:22 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +        private IBlobStore blobStore(Descriptor desc)
Capitalize

2023-05-27 13:49 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +        internal async Task DeleteAsync(Descriptor target, bool isManifest, CancellationToken cancellationToken)
I don't see it's used in test

2023-05-27 13:52 UTC, sammychinedu2ky commented on Oras/Remote/LinkUtils.cs
> +        internal static string ObtainUrl(string url, bool plainHttp)
I need the stream for the other one. for the ObtainUrl I just need the URL and the plainHttp parameter

2023-05-27 13:52 UTC, sammychinedu2ky commented on Oras/Remote/LinkUtils.cs
> +        internal static string ObtainUrl(string url, bool plainHttp)
so its a bit different

2023-05-27 13:53 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            if (resp.Content.Headers.TryGetValues("Docker-Content-Digest", out var digestValues) is var gotValues && !gotValues) return;
Is this equivalent to

```suggestion
            if (!resp.Content.Headers.TryGetValues("Docker-Content-Digest", out var digestValues))
```
?

2023-05-27 13:55 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +            if (resp.Content.Headers.TryGetValues("Docker-Content-Digest", out var digestValues) is var gotValues && !gotValues) return;
yh

2023-05-27 13:58 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +        private async Task<string> CalculateDigestFromResponse(HttpResponseMessage res)
But it has nothing to do with the instance, right?

2023-05-27 14:00 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +        private async Task<string> CalculateDigestFromResponse(HttpResponseMessage res)
Nope

2023-05-27 14:00 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +        private async Task<string> CalculateDigestFromResponse(HttpResponseMessage res)
But was only used there

2023-05-27 14:00 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +                    return (desc, returnedStream);
Why do we need to copy the stream?

2023-05-27 14:01 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +                    return (desc, returnedStream);
It's a way of having full control of the using statement and disposables

2023-05-27 14:04 UTC, sammychinedu2ky commented on Oras/Remote/Repository.cs
> +                    return (desc, returnedStream);
Without it I won't be able to read the from the stream because it would be disposed early

2023-05-27 14:09 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +
Realized that this part shouldn't be hit if the exception was caught.

2023-05-27 14:12 UTC, Wwwsylvia commented on Oras/Remote/Repository.cs
> +            var mediaType = resp.Content.Headers.ContentType.MediaType;
Would any of these be `null`?

2023-05-27 14:19 UTC, sammychinedu2ky commented
Test Coverage at 80%
![image](https://github.com/oras-project/oras-dotnet/assets/36219292/7cfc8aea-249b-4fef-b634-8420655e863d)

2023-05-27 16:09 UTC, Wwwsylvia approved these changes
LGTM

2023-05-27 16:09 UTC, merged