feat: Basic auth
oras-project/oras-dotnet pull request #22
Opened 2023-05-26 05:19 UTC by sammychinedu2ky

fixes https://github.com/oras-project/oras-dotnet/issues/19

2023-05-26 09:19 UTC, Wwwsylvia requested changes

2023-05-26 09:19 UTC, Wwwsylvia commented on Oras/Remote/CustomHttpBasicAuthClient.cs
> +    public class CustomHttpBasicAuthClient : HttpClient
Maybe we can put it in `Remote/Auth` and call it `HttpClientWithBasicAuth`?

2023-05-26 12:03 UTC, Wwwsylvia commented on Oras/Remote/CustomHttpBasicAuthClient.cs
> +        public CustomHttpBasicAuthClient(string username, string password)
We should also set the "oras-dotnet" User-Agent header

2023-05-27 12:24 UTC, sammychinedu2ky commented
Image of test coverage -> 80%
![image](https://github.com/oras-project/oras-dotnet/assets/36219292/1a45e112-0e62-439c-9f63-106c056af213)

2023-05-27 16:15 UTC, closed without merging